name: nfc_manager_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-151.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  another_flutter_splash_screen: ^1.2.0
  animated_splash_screen: ^1.3.0
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  flutter_nfc_kit: ^3.4.2
  flutter_spinkit: ^5.2.1
  material_dialogs: ^1.1.4
  dialogs: ^0.0.7
  package_rename: ^1.5.3
  rename_app: ^1.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
package_rename_config:
  android:
    app_name: NFC Manager App
    package_name: com.nfcmmanager.easy
    override_old_package: com.example.example
    lang: kotlin

  ios:
    app_name: NFC Manager App
    bundle_name: nfcmanager
    package_name: com.nfcmmanager.easy

  web:
    app_name: NFC Manager App
    description: Package to change project configurations.

  linux:
    app_name: NFC Manager App
    package_name: com.nfcmmanager.easy
    exe_name: nfcmanager-linux-x64

  windows:
    app_name: NFC Manager App
    organization: easydigital
    copyright_notice: Copyright Â©ï¸ 2024 easydigital. All rights reserved.
    exe_name: nfcmanager-win32

  macos:
    app_name: NFC Manager App
    package_name: com.nfcmmanager.easy
    copyright_notice: Copyright Â©ï¸ 2024 easydigital. All rights reserved.
